//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
namespace CharacterCreator.Winform.Properties
=======
<<<<<<< HEAD:classwork/MovieLibrary - Original/Itse1430.MovieLib.Host/Properties/Settings.Designer.cs
namespace Itse1430.MovieLib.Host.Properties
=======
namespace CharacterCreator.Winform.Properties
>>>>>>> 68cf341013862ab2bb00b6ceee97f1db28444cf4:labs/Lab 2/CharacterCreator.Winform/Properties/Settings.Designer.cs
>>>>>>> 68cf341013862ab2bb00b6ceee97f1db28444cf4
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute ()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute ("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized (new Settings ())));

        public static Settings Default
        {
            get {
                return defaultInstance;
            }
        }
    }
}
